[config]
"assessAllTests" = true
"autopopulatestemcount" = true
"barlength" = 76 # cm. this shouldn’t ever change, unless the bar is replaced. i.e. the width of a side hit cell.
"barradius" = .8 # 1 cm = 0.32 inches
"calibrationFactor" = 204200 # 22.24 N = 5 lbs
"convert_KgToLbs" = 2.20462262 # kg to lbs
"convert_KgToN" = 1/9.81 # kg to N # CHECK FOR ACCURACY CB 8/9/2022
"convert_NToLbs" = 4.44822
"default_stemheight" = 10.0 # cm
"defaultstemcount" = 33
"dev_guess" = "COM3"
"dev_manual" = "/dev/ttyACM0" # manual override
"dev_manualOverride" = true
"encoderWorked_override" = false # false means encoder will be treated as not working. this is poor code and should be improved.
"ignoreserial" = false
"importFileDataTF" = true
"initial_barbottomOverStemheight_coeff" = 0.8
"location" = "EP425" # "Kambitsch Farm"
"operator" = "Clayton Bennett"
"refreshAllAuto" = false
"sleepSend" = 0.5
"visualizeDatastream" = false # true # set to live graph for data display
"vis" = "nope" #
"wheel diameter" = 31.4136
"coordinates" = "46.592516,-116.946268"
"disReferenced_PeakClick" = false
"useInitialPlot_PeakClick" = false


[notes]
## visualizeDatastream ( search: "def datafeed(" ) is broken right now. Refer to earlier versions (pre v65)for reference of how Bebee left it.

[flexural rigidity parameters]
# INPUT PARAMETERS (EI will be calculated in units of f*l^2)
"f" = 5 # peak force
"h" = 8 # force bar height
"l" = 10 # beam length
"s" = 1 # beam-to-beam spacing
"definite_beam_num = False # # if False, assumes max number of beams at the first beam's max deflection
"beam_count" = 8 # num. of beams in a row (only used if "definite_beam_num" set to True)
