[config]
"stack_direction_groups" = "diagonal_stack"
"stack_direction_subgroups" = "time_stack"
"stack_direction_curves" = "coincident_stack"
"import_style_plugin" =  "import_plugin_CSV_3D"
"export_style_plugin" =  "export_plugin_createFBX_bar_3Dcube"
"color_style_plugin" = "color_plugin_binned_gradient"
"column_time" = "Time"
"column_height" = "Force"
"column_depth" = "Elevation"
"column_color" = "Distance"
"columns_metadata" = ""	
"data_start_idx" = 0
"file_encoding" = "bin"
"file_format" = "FBX"       
"time-series-transcoding" = "null" # null not available in toml before Python 3.11
"keep-true-destroy-false-unassigned-curves" = false
"real-true-normalized-false-scale" = true