''' Global Variables --> Config'''

operator = 'Clayton Bennett'
location = 'EP425' # 'Kambitsch Farm'
coordinates = '46.592516,-116.946268'
script = os.path.basename(__file__)
directory = os.path.dirname(__file__)
operatingsystem = platform.system() #determine OS
# use or sys.plaform instead of platform.system, to avoid importing platform
print("operatingsystem =",operatingsystem)
print("os.getlogin() =",os.getlogin())
print("operator =",operator)
print("location =",location)
today = date.today()
datestring = today.strftime("%b-%d-%Y")
ignoreserial = False # True 
#ignoreserial = True # delete this # if RecordForce.ser.isOpen() == False:
barlength = 76 # cm. this shouldn't ever change, unless the bar is replaced. i.e. the width of a side hit cell.
#dev_manual = 'COM7' # manual override
dev_manual = '/dev/ttyACM0' # manual override
#dev_manual = 'COM7' # manual override
dev_manualOverride = True
useInitialPlot_PeackClick = False
disReferenced_PeakClick = False
barradius = .8 # 1 cm = 0.32 inches
#barradius = 1 # 1 cm = 0.32 inches
default_stemheight = 10.0 # cm
initial_barbottomOverStemheight_coeff = 0.8
convert_KgToLbs = 2.20462262 #kg to lbs
convert_KgToN = 1/9.81 #kg to N # CHECK FOR ACCURACY CB 8/9/2022
convert_NToLbs = 4.44822
#calibrationFactor = 199750 # 23.4 N > 5 lbs; 5 lbs = 22.2411
calibrationFactor = 204200 # 22.24 N = 5 lbs

inchonvert = (((math.pi*(0.764))*31.4136)/359) # converts displacement to inches, wheel diameter = 31.4136
visualizeDatastream = False #True #set to live graph for data display
sleepSend = 0.5
encoderWorked_override = False # False means encoder will be trated as not working. this is poor code and should be improved.
assessAllTests = True
refreshAllAuto = False
autopopulatestemcount = True
defaultstemcount = 33
importFileDataTF = True
#visualizeDatastream = True
# visualizeDatastream ( search: "def datafeed(" ) is broken right now. Refer to earlier versions (pre v65)for reference of how Bebee left it.
vis = 's' # legacy
vis = 'nope' # 